export const routes = {
  customerHome: '/pages/index/index',
  adminLogin: '/pages/login/index',
  ownerDashboard: '/pages/owner/dashboard/index',
  ownerImportUpload: '/pages/owner/import-upload/index',
  ownerDraftReview: '/pages/owner/draft-review/index',
  ownerProducts: '/pages/owner/products/index',
  ownerOrders: '/pages/owner/orders/index',
  ownerMore: '/pages/owner/more/index',
  ownerNoPermission: '/pages/owner/no-permission/index',
  ownerPermissions: '/pages/owner/permissions/index',
  ownerHomepageSettings: '/pages/owner/homepage-settings/index',
  ownerAccountManagement: '/pages/owner/account-management/index',
  staffImageTasks: '/pages/staff/image-tasks/index',
  customerProductList: '/pages/customer/product-list/index',
  customerFavorites: '/pages/customer/favorites/index',
  customerShoppingBag: '/pages/customer/shopping-bag/index',
  customerMine: '/pages/customer/mine/index',
  customerProfile: '/pages/customer/profile/index',
  customerWallet: '/pages/customer/wallet/index',
  customerAddress: '/pages/customer/address/index',
  customerOrders: '/pages/customer/orders/index',
  customerOrderDetail: '/pages/customer/order-detail/index',
  customerProductDetail: '/pages/customer/product-detail/index',
} as const

export type AppRoute = (typeof routes)[keyof typeof routes]
